### ISSUE TITLE
SVN connection error

### ISSUE THREAD

**Issue by Curlychump** [zenith391/OCEmu#46]
svn: E170013: Unable to connect to a repository at URL 'https://github.com/MightyPirates/OpenComputers/tree/master-MC1.7.10/src/main/resources/assets/opencomputers/lua'

i dont have any other information, sorry

**Comment by Kimapr** [comment]
Github removed SVN support this year: https://github.blog/changelog/2024-01-08-subversion-has-been-sunset/

The build process should be fixed to remove the dependency on Github's SVN support.

**Comment by Curlychump** [comment]
As in the problem is fixed, or should probably be fixed soon

**Comment by Curlychump** [comment]
Issue solved: I just manually downloaded and moved all the required files, i also had the incorrect version of lua (woops) so i just had to switch out the binaries. Ill see if i can fix the make file and merge to fix this

**Comment by Kimapr** [comment]
I'd say issue NOT solved: the underlying problem remains. i think it should remain open.
